var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8c0029d4._.js")
R.c("server/chunks/ssr/_7edddb3c._.js")
R.c("server/chunks/ssr/_50f9b3d6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e925b2be._.js")
R.c("server/chunks/ssr/[root-of-the-server]__46e4e698._.js")
R.c("server/chunks/ssr/node_modules__pnpm_f61de835._.js")
R.c("server/chunks/ssr/apps_frontend_app_30a646e1._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_global-error_b6393c51.js")
R.c("server/chunks/ssr/[root-of-the-server]__48858a94._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_90cb04ec._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_forbidden_0dca5766.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_unauthorized_2a2ce518.js")
R.c("server/chunks/ssr/_d2c0d240._.js")
R.c("server/chunks/ssr/apps_frontend_app_(auth)_template_tsx_71200db3._.js")
R.c("server/chunks/ssr/apps_frontend__next-internal_server_app_(auth)_login_page_actions_54af1f69.js")
R.m(51644)
module.exports=R.m(51644).exports
