var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/admin/products/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ceca9596._.js")
R.c("server/chunks/ssr/_7edddb3c._.js")
R.c("server/chunks/ssr/_9a0af20d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e925b2be._.js")
R.c("server/chunks/ssr/[root-of-the-server]__46e4e698._.js")
R.c("server/chunks/ssr/node_modules__pnpm_f61de835._.js")
R.c("server/chunks/ssr/apps_frontend_app_30a646e1._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_global-error_b6393c51.js")
R.c("server/chunks/ssr/[root-of-the-server]__519f839b._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_90cb04ec._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_forbidden_0dca5766.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_unauthorized_2a2ce518.js")
R.c("server/chunks/ssr/apps_frontend_app_(admin)_layout_tsx_d742eb81._.js")
R.c("server/chunks/ssr/0da96_frontend__next-internal_server_app_(admin)_admin_products_page_actions_18c27f1d.js")
R.m(62743)
module.exports=R.m(62743).exports
