var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/admin/orders/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f87e1928._.js")
R.c("server/chunks/ssr/_7edddb3c._.js")
R.c("server/chunks/ssr/_2ca8731f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d8546ad._.js")
R.c("server/chunks/ssr/f53db_next_dist_c96e53ff._.js")
R.c("server/chunks/ssr/node_modules__pnpm_f61de835._.js")
R.c("server/chunks/ssr/apps_frontend_app_30a646e1._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_global-error_b6393c51.js")
R.c("server/chunks/ssr/[root-of-the-server]__519f839b._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_90cb04ec._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_forbidden_0dca5766.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_unauthorized_2a2ce518.js")
R.c("server/chunks/ssr/apps_frontend_app_(admin)_layout_tsx_d742eb81._.js")
R.c("server/chunks/ssr/0da96_frontend__next-internal_server_app_(admin)_admin_orders_page_actions_94f51bef.js")
R.m(51699)
module.exports=R.m(51699).exports
