var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(main)/orders/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bd6af6d3._.js")
R.c("server/chunks/ssr/_7edddb3c._.js")
R.c("server/chunks/ssr/_d69cf80c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e925b2be._.js")
R.c("server/chunks/ssr/[root-of-the-server]__46e4e698._.js")
R.c("server/chunks/ssr/node_modules__pnpm_f61de835._.js")
R.c("server/chunks/ssr/apps_frontend_app_30a646e1._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_global-error_b6393c51.js")
R.c("server/chunks/ssr/[root-of-the-server]__48858a94._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_90cb04ec._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_forbidden_0dca5766.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_unauthorized_2a2ce518.js")
R.c("server/chunks/ssr/_389736f3._.js")
R.c("server/chunks/ssr/apps_frontend_app_(main)_template_tsx_0e60cce6._.js")
R.c("server/chunks/ssr/apps_frontend__next-internal_server_app_(main)_orders_page_actions_e54ced06.js")
R.m(21337)
module.exports=R.m(21337).exports
