var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(admin)/admin/orders/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3d9d54cf._.js")
R.c("server/chunks/ssr/_7edddb3c._.js")
R.c("server/chunks/ssr/_e1da16d7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e925b2be._.js")
R.c("server/chunks/ssr/[root-of-the-server]__46e4e698._.js")
R.c("server/chunks/ssr/node_modules__pnpm_f61de835._.js")
R.c("server/chunks/ssr/apps_frontend_app_30a646e1._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_global-error_b6393c51.js")
R.c("server/chunks/ssr/[root-of-the-server]__48858a94._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_90cb04ec._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_forbidden_0dca5766.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_unauthorized_2a2ce518.js")
R.c("server/chunks/ssr/apps_frontend_app_(admin)_layout_tsx_d742eb81._.js")
R.c("server/chunks/ssr/apps_frontend_app_(admin)_template_tsx_477fbc93._.js")
R.c("server/chunks/ssr/0da96_frontend__next-internal_server_app_(admin)_admin_orders_page_actions_94f51bef.js")
R.m(89087)
module.exports=R.m(89087).exports
