var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__58fe0cf8._.js")
R.c("server/chunks/ssr/_7edddb3c._.js")
R.c("server/chunks/ssr/f53db_next_dist_esm_build_templates_app-page_25091ebd.js")
R.c("server/chunks/ssr/[root-of-the-server]__7ae0f6c4._.js")
R.c("server/chunks/ssr/f53db_next_dist_c96e53ff._.js")
R.c("server/chunks/ssr/node_modules__pnpm_f61de835._.js")
R.c("server/chunks/ssr/apps_frontend_app_30a646e1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__519f839b._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_90cb04ec._.js")
R.c("server/chunks/ssr/f53db_next_dist_client_components_builtin_forbidden_0dca5766.js")
R.c("server/chunks/ssr/apps_frontend__next-internal_server_app__not-found_page_actions_e8668f62.js")
R.m(82766)
module.exports=R.m(82766).exports
